apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-worker-31225
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/service-worker-31225
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
